apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: siscom
data:
  # Aplicação
  APP_NAME: "siscom"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "https://siga.dev.br"
  
  # Database
  DB_CONNECTION: "pgsql"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_DATABASE: "siscom"
  DB_USERNAME: "siscom"
  
  # Redis
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # Cache & Session
  CACHE_DRIVER: "redis"
  SESSION_DRIVER: "redis"
  QUEUE_CONNECTION: "redis"
  
  # File Storage
  FILESYSTEM_DISK: "do_spaces"
  DO_SPACES_ENDPOINT: ""
  DO_SPACES_REGION: ""
  DO_SPACES_BUCKET: ""
  
  # Mail
  MAIL_MAILER: "smtp"
  MAIL_HOST: "smtp.mailtrap.io"
  MAIL_PORT: "2525"
  MAIL_ENCRYPTION: "tls"
  MAIL_FROM_ADDRESS: "noreply@siga.dev.br"
  MAIL_FROM_NAME: "siscom"
