apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: siscom
type: Opaque
stringData:
  # Laravel
  APP_KEY: "base64:pC4npdjmQdsshTgFi6hHWTHqNW/CHd4gkfdA+hNreFc="
  
  # Database
  DB_PASSWORD: "cuufNleNJCEFmO6NJsNgPOpKC"
  
  # Redis
  REDIS_PASSWORD: "IyKq0VFln4tssKZdrZMZk4qmf"
  
  # DigitalOcean Spaces / S3 (opcional)
  DO_SPACES_KEY: ""
  DO_SPACES_SECRET: ""
